### ISSUE TITLE
[BUG] Bot doesn't add contributors pinged in a submission post as authors if they're not in the server

### ISSUE THREAD

**Issue by Pomi108** [Faithful-Resource-Pack/Discord-Bot#168] opened 2022-01-30 17:57 UTC
**Describe the bug**
When submitting a texture, the bot is supposed to add people that are pinged in the comment as co-authors. The bot, however, does not do this if said pinged user is not in the server.

**To Reproduce**
Steps to reproduce the behaviour:
1. Upload a valid texture to #submit-textures (any)
2. Ping any user that's not in the server (for example `<@!373928073176809485>` (LethalChicken) in the comment
3. Pinged user is not added into the Authors field

**Expected behavior**
The pinged user should be added as a co-author.

**Screenshots**
![Snímek obrazovky 2022-01-30 v 18 45 42](https://user-images.githubusercontent.com/59484948/151711285-bdeb208c-70f7-48b1-8939-9d21d2caf403.png)
(https://canary.discord.com/channels/773983706582482946/773987409993793546/933532626906665030)

**Comment by Juknum** [comment] 2022-03-05 00:00
This won't be fixed in profit of the TS version

**Comment by RobertRR11** [comment] 2022-03-05 09:26
> This won't be fixed in profit of the TS version

what?

**Comment by 3vorp** [comment] 2023-06-11 05:24
I've been looking into this for a few days now, and like what you've said, there's a bit of a conceptual flaw. You can't really mention a user that's not in the server anyways, and I'm pretty sure the problem is with the fact that the bot can't grab the user properly or something like that.

I have two potential solutions for this, both of which having potential to work.
- The first is to use some sort of character (similarly to how ID quoting uses square brackets and a hashtag) to denote adding an author, in addition to the current ping system. My personal favorite option would be curly brackets since there's rarely a reason to use them otherwise (a potential submission comment could be "credit to {Cituation}, fixed a false line"). 
   - Potential problems with this include authors with similar names, and being able to fetch them into the submission embed in a reasonably efficient manner.
   - However, this would be the cleaner solution and would have the benefits of allowing people to mention authors without pinging them many times.
- Alternatively, we could use discord IDs. The bot would search for any numbers in the submission description and try to match them up with a contributor in the database if possible. 
   - This would likely be the easier option, but would be a lot jankier for users to use since they'd have to have a list of all user ids at once.
   - This has the same benefit as the previous solution of allowing people to mention co-authors without pinging them, and would probably be easier to parse on the bot end as well.

**Comment by 3vorp** [comment] 2023-06-11 17:24
technically this has been resolved in https://github.com/Faithful-Resource-Pack/Discord-Bot/commit/3e48543d93611e331b25d91884d2aa5e07a8030c, since I now run a global regex to pick up all mentions, not just ones the bot recognizes — I still want to implement the curly bracket solution for convenience rather than it being a bug though

**Closed** 2023-06-11 17:58 UTC
Labels: bug
